# Generated by Django 5.0.2 on 2024-11-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FallDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(upload_to='snapshots/')),
                ('status', models.CharField(default='Fall Detected', max_length=50)),
            ],
        ),
    ]
