# Generated by Django 5.0.2 on 2024-11-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_falldetectionlog_delete_falldetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='falldetectionlog',
            name='snapshot_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='falldetectionlog',
            name='status',
            field=models.CharField(choices=[('Fall', 'Fall'), ('No Fall', 'No Fall')], max_length=100),
        ),
    ]
