# Generated by Django 5.0.2 on 2024-11-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_alter_falldetectionlog_snapshot_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_url', models.URLField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='FallDetectionLog',
        ),
    ]
