services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python -c "import matplotlib.pyplot as plt; plt.plot(); plt.close()"
      gunicorn fall_detection.wsgi --bind 0.0.0.0:$PORT --timeout 600 --keep-alive 120
